# Generated by Django 5.2.1 on 2025-05-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_region_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='population',
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('house', 'Дом'), ('apartment', 'Квартира'), ('hotel', 'Гостиница')], max_length=20)),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=10)),
                ('apartment_number', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.district')),
            ],
        ),
    ]
