# Generated by Django 5.2.1 on 2025-05-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_district_population_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='apartment_number',
        ),
    ]
