# Generated by Django 5.2.1 on 2025-05-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_remove_property_latitude_remove_property_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('people_count', models.PositiveIntegerField()),
                ('criteria', models.TextField(blank=True)),
                ('budget', models.CharField(max_length=50)),
            ],
        ),
    ]
