# Generated by Django 5.2.1 on 2025-05-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_houserequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('guests', models.IntegerField()),
                ('criteria', models.TextField()),
                ('budget', models.CharField(max_length=50)),
            ],
        ),
    ]
