# Generated by Django 5.2.1 on 2025-05-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_requestform'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
