# Generated by Django 5.2.1 on 2025-05-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_property_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
