# Generated by Django 5.2.1 on 2025-05-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_alter_house_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('house', 'Дом'), ('apartment', 'Квартира'), ('hotel', 'Гостиница'), ('hostel', 'хостел')], max_length=20),
        ),
    ]
