# Generated by Django 5.2.1 on 2025-05-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='features',
            field=models.ManyToManyField(blank=True, to='houses.feature'),
        ),
    ]
