# Generated by Django 5.2.1 on 2025-05-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_alter_house_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
