# Generated by Django 5.2.1 on 2025-05-26 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_bookingrequest_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('features', models.ManyToManyField(blank=True, to='houses.feature')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.location')),
            ],
        ),
    ]
