# Generated by Django 5.2.1 on 2025-05-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, to='houses.feature'),
        ),
    ]
