# Generated by Django 5.2.1 on 2025-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0015_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('house', 'Дом'), ('apartment', 'Квартира'), ('hotel', 'Гостиница'), ('hostel', 'Хостел')], max_length=20),
        ),
    ]
